events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout  65;

    # 1) HTTP -> HTTPS redirect
    server {
        listen 80;
        server_name markocakmak.com www.markocakmak.com;
        return 301 https://$host$request_uri;
    }

    # 2) HTTPS server
    server {
        listen 443 ssl;
        server_name markocakmak.com www.markocakmak.com;

        ssl_certificate     /etc/letsencrypt/live/markocakmak.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/markocakmak.com/privkey.pem;

        root /var/www/public;
        index index.php index.html;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            fastcgi_pass php-fpm:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            fastcgi_param HTTPS on;
            fastcgi_param SERVER_PORT 443;
            fastcgi_param HTTP_X_FORWARDED_PROTO https;

            include fastcgi_params;
        }
    }
}
